server {
    listen 8080;
    server_name localhost;

    location /beauty.ai/ {
        alias /usr/share/nginx/html/beauty.ai/;
        index index.html index.htm;
        try_files $uri $uri/ /beauty.ai/index.html;
    }

    location / {
        return 301 $scheme://$https_host/beauty.ai/;
    }
    location /api {
      proxy_pass https://beautyaiservice.polandcentral.cloudapp.azure.com:8000;

      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }
    location /admin {
      proxy_pass https://beautyaiservice.polandcentral.cloudapp.azure.com:8000;

      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }
}
