# Generated by Django 6.0.7 on 2026-08-22 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.TextField()),
                ('search_type', models.CharField(choices=[('ai_search', 'AI search'), ('manual', 'Manual'), ('quick_filter', 'Quick filter')], max_length=20)),
                ('search_datetime', models.DateTimeField(auto_now_add=True)),
                ('recommendation_accepted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_type', models.CharField(choices=[('ai_search', 'AI search'), ('manual', 'Manual'), ('quick_filter', 'Quick filter')], max_length=20)),
                ('quick_filter_label', models.CharField(blank=True, max_length=100, null=True)),
                ('click_datetime', models.DateTimeField(auto_now_add=True)),
                ('led_to_booking', models.BooleanField(default=False)),
            ],
        ),
    ]
