# Generated by Django 6.0.7 on 2026-08-22 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0002_initial'),
        ('beauty_service', '0001_initial'),
        ('salons', '0002_initial'),
        ('search', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='searchquery',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_queries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='searchquery',
            name='recommended_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_recommendations', to='users.master'),
        ),
        migrations.AddField(
            model_name='searchquery',
            name='recommended_salon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_recommendations', to='salons.salon'),
        ),
        migrations.AddField(
            model_name='searchquery',
            name='recommended_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_recommendations', to='beauty_service.service'),
        ),
        migrations.AddField(
            model_name='userclick',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_clicks', to='appointments.appointment'),
        ),
        migrations.AddField(
            model_name='userclick',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clicks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userclick',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_clicks', to='users.master'),
        ),
        migrations.AddField(
            model_name='userclick',
            name='salon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_clicks', to='salons.salon'),
        ),
        migrations.AddField(
            model_name='userclick',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_clicks', to='beauty_service.service'),
        ),
        migrations.AddField(
            model_name='searchquery',
            name='click',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='search.userclick'),
        ),
    ]
