# Generated by Django 6.0.7 on 2026-08-19 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('beauty_service', '0001_initial'),
        ('salons', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='users.master'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='salon',
            field=models.ForeignKey(db_column='salon_id', on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='salons.salon'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(db_column='service_id', on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='beauty_service.service'),
        ),
        migrations.AddField(
            model_name='appointmentreminder',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='appointments.appointment'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(condition=models.Q(('end__gt', models.F('start'))), name='appointments_check'),
        ),
        migrations.AddConstraint(
            model_name='appointmentreminder',
            constraint=models.UniqueConstraint(fields=('appointment', 'reminder_type'), name='unique_reminder_type_per_appointment'),
        ),
    ]
