# Generated by Django 6.0.7 on 2026-08-11 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentreminder',
            name='is_client_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointmentreminder',
            name='is_master_sent',
            field=models.BooleanField(default=False),
        ),
    ]
