# Generated by Django 6.0.7 on 2026-08-22 12:53

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('city_name', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('coordinates', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('city_tier', models.CharField(blank=True, choices=[('big', 'Big'), ('small', 'Small')], max_length=5, null=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('country', 'city_name', 'address'), name='unique_location_address')],
            },
        ),
    ]
