# Generated by Django 6.0.7 on 2026-08-22 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payer_type', models.CharField(choices=[('solo_master', 'Solo master'), ('salon', 'Salon')], max_length=20)),
                ('commission_rate', models.DecimalField(decimal_places=3, max_digits=5)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commission', to='appointments.appointment')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='UAH', max_length=3)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('apple_pay', 'Apple Pay'), ('google_pay', 'Google Pay')], max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='appointments.appointment')),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
    ]
