# Generated by Django 6.0.7 on 2026-08-19 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salons', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='masters',
            field=models.ManyToManyField(related_name='salons', through='users.MasterSalon', to='users.master'),
        ),
        migrations.AddField(
            model_name='salon',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salonworkinghours',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='salons.salon'),
        ),
        migrations.AddConstraint(
            model_name='cachedsalon',
            constraint=models.UniqueConstraint(fields=('name', 'address'), name='unique_cached_salon_name_address'),
        ),
        migrations.AddConstraint(
            model_name='salon',
            constraint=models.UniqueConstraint(fields=('name', 'address'), name='unique_partner_salon_name_address'),
        ),
        migrations.AddConstraint(
            model_name='salonworkinghours',
            constraint=models.UniqueConstraint(fields=('salon', 'weekday'), name='unique_salon_weekday'),
        ),
        migrations.AddConstraint(
            model_name='salonworkinghours',
            constraint=models.CheckConstraint(condition=models.Q(('is_closed', True), models.Q(('opening_time__isnull', False), ('closing_time__isnull', False), ('opening_time__lt', models.F('closing_time'))), _connector='OR'), name='valid_salon_working_hours'),
        ),
    ]
