# Generated by Django 6.0.7 on 2026-08-22 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beauty_service', '0001_initial'),
        ('referral_events', '0001_initial'),
        ('salons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='linktracking',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='link_tracking_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='linktracking',
            name='salon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='link_tracking_events', to='salons.salon'),
        ),
        migrations.AddField(
            model_name='linktracking',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='link_tracking_events', to='beauty_service.service'),
        ),
        migrations.AddField(
            model_name='referralprogram',
            name='referred_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referralprogram',
            name='referring_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='linktracking',
            index=models.Index(fields=['created_at'], name='referral_ev_created_734a30_idx'),
        ),
        migrations.AddIndex(
            model_name='linktracking',
            index=models.Index(fields=['event_type'], name='referral_ev_event_t_f40e29_idx'),
        ),
        migrations.AddIndex(
            model_name='linktracking',
            index=models.Index(fields=['salon', 'created_at'], name='referral_ev_salon_i_eb1588_idx'),
        ),
    ]
