# Generated by Django 6.0.7 on 2026-08-11 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beauty_service', '0001_initial'),
        ('referral_events', '0001_initial'),
        ('salons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='referralevent',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referral_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referralevent',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_events', to='salons.salon'),
        ),
        migrations.AddField(
            model_name='referralevent',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referral_events', to='beauty_service.service'),
        ),
        migrations.AddIndex(
            model_name='referralevent',
            index=models.Index(fields=['created_at'], name='referral_ev_created_f66bda_idx'),
        ),
        migrations.AddIndex(
            model_name='referralevent',
            index=models.Index(fields=['session_id'], name='referral_ev_session_e0af96_idx'),
        ),
        migrations.AddIndex(
            model_name='referralevent',
            index=models.Index(fields=['event_type'], name='referral_ev_event_t_16e0a9_idx'),
        ),
        migrations.AddIndex(
            model_name='referralevent',
            index=models.Index(fields=['salon'], name='referral_ev_salon_i_494554_idx'),
        ),
        migrations.AddIndex(
            model_name='referralevent',
            index=models.Index(fields=['service'], name='referral_ev_service_b15336_idx'),
        ),
        migrations.AddIndex(
            model_name='referralevent',
            index=models.Index(fields=['salon', 'created_at'], name='referral_ev_salon_i_f67d49_idx'),
        ),
    ]
