# Generated by Django 6.0.7 on 2026-09-14 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral_events', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralprogram',
            name='reward_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('earned', 'Earned'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('rewarded', 'Rewarded'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
    ]
