# Generated by Django 6.0.7 on 2026-08-10 13:11

import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
import users.managers
import users.services.media_path
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('beauty_service', '0001_initial'),
        ('salons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(max_length=150, verbose_name='last name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=users.services.media_path.generate_upload_path)),
                ('google_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('gender', models.CharField(blank=True, choices=[('man', 'Man'), ('woman', 'Woman')], max_length=10, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('last_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('last_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('registration_date_user', models.DateTimeField(auto_now_add=True)),
                ('last_update_user', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('preferred_salons', models.ManyToManyField(blank=True, related_name='followers', to='salons.salon')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', users.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(blank=True, max_length=255, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('years_of_experience', models.PositiveIntegerField()),
                ('registration_date_master', models.DateTimeField(auto_now_add=True)),
                ('last_update_master', models.DateTimeField(auto_now=True)),
                ('account_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blocked', 'Blocked'), ('deleted', 'Deleted'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='master', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_master_relations', to=settings.AUTH_USER_MODEL)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_relations', to='users.master')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='DayOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days_off', to='users.master')),
            ],
            options={
                'ordering': ('start_date',),
            },
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_masters',
            field=models.ManyToManyField(related_name='favorited_by', through='users.FavoriteMaster', to='users.master'),
        ),
        migrations.CreateModel(
            name='MasterSalon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_salons', to='users.master')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_salons', to='salons.salon')),
            ],
        ),
        migrations.CreateModel(
            name='MasterService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_services', to='users.master')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_services', to='beauty_service.service')),
            ],
        ),
        migrations.AddField(
            model_name='master',
            name='services',
            field=models.ManyToManyField(related_name='masters', through='users.MasterService', to='beauty_service.service'),
        ),
        migrations.CreateModel(
            name='WorkingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')])),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('is_working_day', models.BooleanField(default=True)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_schedule', to='users.master')),
            ],
            options={
                'ordering': ('weekday', 'start_time'),
            },
        ),
        migrations.AddConstraint(
            model_name='favoritemaster',
            constraint=models.UniqueConstraint(fields=('client', 'master'), name='unique_client_favorite_masters'),
        ),
        migrations.AddConstraint(
            model_name='mastersalon',
            constraint=models.UniqueConstraint(fields=('master', 'salon'), name='unique_master_salon'),
        ),
        migrations.AddConstraint(
            model_name='masterservice',
            constraint=models.UniqueConstraint(fields=('master', 'service'), name='unique_master_service'),
        ),
    ]
