# Generated by Django 6.0.7 on 2026-08-11 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workingschedule',
            options={'ordering': ('weekday',)},
        ),
        migrations.AddConstraint(
            model_name='workingschedule',
            constraint=models.UniqueConstraint(fields=('master', 'weekday'), name='unique_master_working_schedule_day'),
        ),
    ]
